# Generated by Django 5.0 on 2023-12-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_owner_delete_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('I', 'In Progress'), ('P', 'Done'), ('D', 'Pending')], default='P', max_length=1),
        ),
    ]
