# Generated by Django 5.0 on 2024-01-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todo_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.ImageField(blank=True, default='https://m.media-amazon.com/images/I/31RvOPlfH7L.png', upload_to=''),
        ),
    ]
